export const fetchedStockData = {
  rawData: [
    [
      'id ',
      'Categoría',
      'Tipo',
      'Nombre',
      'Stock',
      'PRECIO COSTO',
      'Porcentaje recargo',
      'Precio público',
      'Ganancia',
      'Proveedor',
      'Descripción',
      'Imagen',
      'Destilería',
      'Alcohol %',
    ],
    [
      '#001',
      'Fernet',
      'Fernet',
      'Fernet branca 1L',
      395,
      8800,
      33,
      11704,
      2904,
      'mariano o fabrica ',
      'Elaborada a base de hierbas (mirra, ruibarbo, manzanilla, cardamomo y azafrán, entre otras)',
      'https://drive.google.com/uc?export=view&id=1ToG5gKlwY8nKk8uXgHGqNFk_qDIYMpQM',
      '',
      39,
    ],
    [
      '#002',
      'Fernet',
      'Fernet',
      'Fernet branca 750',
      528,
      6700,
      33,
      8911,
      2211,
      'mariano o fabrica ',
      'Elaborada a base de hierbas (mirra, ruibarbo, manzanilla, cardamomo y azafrán, entre otras)',
      'testing-no-image-url',
      '',
      39,
    ],
    ['#003', '', '', '', '', '', ''],
    ['#004', '', '', '', 528, 6700, 33, 8911, 2211],
    ['*005', '', 'testing-not-category', 4756, '', '', ''],
    ['#006', 1888],
    [
      '#007',
      'Vodka',
      'Vodka',
      'Absolut mango 750',
      35,
      15060,
      30,
      19578,
      4518,
      'aristos y exquisitos ',
      'Notas de mango maduros junto con un sabor a piña y maracuyá',
      'https://drive.google.com/uc?export=view&id=1FYuyLCcIwBe6mra6rG-Ual5VZ_59yYx9',
      '',
      40,
    ],
    [
      '#008',
      'Vodka',
      'Vodka',
      'Absolut mandarina 750',
      3,
      15060,
      30,
      19578,
      4518,
      'aristos y exquisitos ',
      'Sabor a mandarina mezclados con un toque de la cáscara de naranja.',
      'https://drive.google.com/uc?export=view&id=1xuCe_se5t6WLgCqpaFDdKvd6vxxCefpg',
      '',
      40,
    ],
    [
      '#009',
      'Vodka',
      'Vodka',
      'Absolut Lime 750',
      3,
      15060,
      30,
      19578,
      4518,
      'aristos y exquisitos ',
      'Notas citricas de limon y lima.',
      'https://drive.google.com/uc?export=view&id=1OeQUqUg0Avj-WAkANc9jgMgA7266YB1x',
      '',
      40,
    ],
    [
      '#010',
      'Vodka',
      'Vodka',
      'Absolut vainilla 750',
      0,
      0,
      0,
      0,
      0,
      'aristos y exquisitos ',
      'Combina el carácter de la vainilla, el tofe y sabores de caramelo',
      'https://drive.google.com/uc?export=view&id=1r7-Hsbi1G6vcdP53v3SGeBxnKHMIXXsJ',
      '',
      40,
    ],
  ],
  headerIndexes: [0, 1, 2, 3, 10, 11, 12, 13, 4, 7],
};

export const buildedStockData = [
  {
    id: '#001',
    category: 'Fernet',
    type: 'Fernet',
    name: 'Fernet branca 1L',
    description: 'Elaborada a base de hierbas (mirra, ruibarbo, manzanilla, cardamomo y azafrán, entre otras)',
    imageID: '1ToG5gKlwY8nKk8uXgHGqNFk_qDIYMpQM',
    imageURL: 'https://drive.google.com/uc?export=view&id=1ToG5gKlwY8nKk8uXgHGqNFk_qDIYMpQM',
    destillery: '',
    alcohol: 39,
    stock: true,
    price: 11704,
    isCombo: false,
  },
  {
    id: '#002',
    category: 'Fernet',
    type: 'Fernet',
    name: 'Fernet branca 750',
    description: 'Elaborada a base de hierbas (mirra, ruibarbo, manzanilla, cardamomo y azafrán, entre otras)',
    imageID: 'testing-no-image-url',
    imageURL: 'testing-no-image-url',
    destillery: '',
    alcohol: 39,
    stock: true,
    price: 8911,
    isCombo: false,
  },
  {
    id: '#006',
    category: 1888,
    type: undefined,
    name: undefined,
    description: undefined,
    imageID: undefined,
    imageURL: undefined,
    destillery: undefined,
    alcohol: undefined,
    stock: false,
    price: undefined,
    isCombo: false,
  },
  {
    id: '#007',
    category: 'Vodka',
    type: 'Vodka',
    name: 'Absolut mango 750',
    description: 'Notas de mango maduros junto con un sabor a piña y maracuyá',
    imageID: '1FYuyLCcIwBe6mra6rG-Ual5VZ_59yYx9',
    imageURL: 'https://drive.google.com/uc?export=view&id=1FYuyLCcIwBe6mra6rG-Ual5VZ_59yYx9',
    destillery: '',
    alcohol: 40,
    stock: true,
    price: 19578,
    isCombo: false,
  },
  {
    id: '#008',
    category: 'Vodka',
    type: 'Vodka',
    name: 'Absolut mandarina 750',
    description: 'Sabor a mandarina mezclados con un toque de la cáscara de naranja.',
    imageID: '1xuCe_se5t6WLgCqpaFDdKvd6vxxCefpg',
    imageURL: 'https://drive.google.com/uc?export=view&id=1xuCe_se5t6WLgCqpaFDdKvd6vxxCefpg',
    destillery: '',
    alcohol: 40,
    stock: true,
    price: 19578,
    isCombo: false,
  },
  {
    id: '#009',
    category: 'Vodka',
    type: 'Vodka',
    name: 'Absolut Lime 750',
    description: 'Notas citricas de limon y lima.',
    imageID: '1OeQUqUg0Avj-WAkANc9jgMgA7266YB1x',
    imageURL: 'https://drive.google.com/uc?export=view&id=1OeQUqUg0Avj-WAkANc9jgMgA7266YB1x',
    destillery: '',
    alcohol: 40,
    stock: true,
    price: 19578,
    isCombo: false,
  },
  {
    id: '#010',
    category: 'Vodka',
    type: 'Vodka',
    name: 'Absolut vainilla 750',
    description: 'Combina el carácter de la vainilla, el tofe y sabores de caramelo',
    imageID: '1r7-Hsbi1G6vcdP53v3SGeBxnKHMIXXsJ',
    imageURL: 'https://drive.google.com/uc?export=view&id=1r7-Hsbi1G6vcdP53v3SGeBxnKHMIXXsJ',
    destillery: '',
    alcohol: 40,
    stock: false,
    price: 0,
    isCombo: false,
  },
];

export const testStockMapBuilding = {
  1888: [
    {
      id: '#006',
      category: 1888,
      type: undefined,
      name: undefined,
      description: undefined,
      imageID: undefined,
      imageURL: undefined,
      destillery: undefined,
      alcohol: undefined,
      stock: false,
      price: undefined,
      isCombo: false,
    },
  ],
  Fernet: [
    {
      id: '#001',
      category: 'Fernet',
      type: 'Fernet',
      name: 'Fernet branca 1L',
      description: 'Elaborada a base de hierbas (mirra, ruibarbo, manzanilla, cardamomo y azafrán, entre otras)',
      imageID: '1ToG5gKlwY8nKk8uXgHGqNFk_qDIYMpQM',
      imageURL: 'https://drive.google.com/uc?export=view&id=1ToG5gKlwY8nKk8uXgHGqNFk_qDIYMpQM',
      destillery: '',
      alcohol: 39,
      stock: true,
      price: 11704,
      isCombo: false,
    },
    {
      id: '#002',
      category: 'Fernet',
      type: 'Fernet',
      name: 'Fernet branca 750',
      description: 'Elaborada a base de hierbas (mirra, ruibarbo, manzanilla, cardamomo y azafrán, entre otras)',
      imageID: 'testing-no-image-url',
      imageURL: 'testing-no-image-url',
      destillery: '',
      alcohol: 39,
      stock: true,
      price: 8911,
      isCombo: false,
    },
  ],
  Vodka: [
    {
      id: '#007',
      category: 'Vodka',
      type: 'Vodka',
      name: 'Absolut mango 750',
      description: 'Notas de mango maduros junto con un sabor a piña y maracuyá',
      imageID: '1FYuyLCcIwBe6mra6rG-Ual5VZ_59yYx9',
      imageURL: 'https://drive.google.com/uc?export=view&id=1FYuyLCcIwBe6mra6rG-Ual5VZ_59yYx9',
      destillery: '',
      alcohol: 40,
      stock: true,
      price: 19578,
      isCombo: false,
    },
    {
      id: '#008',
      category: 'Vodka',
      type: 'Vodka',
      name: 'Absolut mandarina 750',
      description: 'Sabor a mandarina mezclados con un toque de la cáscara de naranja.',
      imageID: '1xuCe_se5t6WLgCqpaFDdKvd6vxxCefpg',
      imageURL: 'https://drive.google.com/uc?export=view&id=1xuCe_se5t6WLgCqpaFDdKvd6vxxCefpg',
      destillery: '',
      alcohol: 40,
      stock: true,
      price: 19578,
      isCombo: false,
    },
    {
      id: '#009',
      category: 'Vodka',
      type: 'Vodka',
      name: 'Absolut Lime 750',
      description: 'Notas citricas de limon y lima.',
      imageID: '1OeQUqUg0Avj-WAkANc9jgMgA7266YB1x',
      imageURL: 'https://drive.google.com/uc?export=view&id=1OeQUqUg0Avj-WAkANc9jgMgA7266YB1x',
      destillery: '',
      alcohol: 40,
      stock: true,
      price: 19578,
      isCombo: false,
    },
    {
      id: '#010',
      category: 'Vodka',
      type: 'Vodka',
      name: 'Absolut vainilla 750',
      description: 'Combina el carácter de la vainilla, el tofe y sabores de caramelo',
      imageID: '1r7-Hsbi1G6vcdP53v3SGeBxnKHMIXXsJ',
      imageURL: 'https://drive.google.com/uc?export=view&id=1r7-Hsbi1G6vcdP53v3SGeBxnKHMIXXsJ',
      destillery: '',
      alcohol: 40,
      stock: false,
      price: 0,
      isCombo: false,
    },
  ],
};

export const testStockCache = [
  {
    category: 'Fernet',
    'firestoreName-ID': 'ZTKZiMQzMZudQdxT1djz',
    firestoreName: 'projects/stock-backend-392114/databases/(default)/documents/categories-test/ZTKZiMQzMZudQdxT1djz',
    data: '[{"id":"#001","isCombo":false,"category":"Fernet","type":"Fernet","name":"Fernet branca 1L","description":"Elaborada a base de hierbas (mirra, ruibarbo, manzanilla, cardamomo y azafrán, entre otras)","imageID":"1ToG5gKlwY8nKk8uXgHGqNFk_qDIYMpQM","imageURL":"https://drive.google.com/uc?export=view&id=1ToG5gKlwY8nKk8uXgHGqNFk_qDIYMpQM","destillery":"","alcohol":39,"stock":true,"price":11704},{"id":"#002","isCombo":false,"category":"Fernet","type":"Fernet","name":"Fernet branca 750","description":"Elaborada a base de hierbas (mirra, ruibarbo, manzanilla, cardamomo y azafrán, entre otras)","imageID":"1I0IZkFFBqau974LYcUkvl-FzbKn69w8i","imageURL":"https://drive.google.com/uc?export=view&id=1I0IZkFFBqau974LYcUkvl-FzbKn69w8i","destillery":"","alcohol":39,"stock":true,"price":8911},{"id":"#003","isCombo":false,"category":"Fernet","type":"Fernet","name":"Fernet branca 450","description":"Elaborada a base de hierbas (mirra, ruibarbo, manzanilla, cardamomo y azafrán, entre otras)","imageID":"1h0J3MwZqbJ8GOkkpsdAAcbOKoGShenhI","imageURL":"https://drive.google.com/uc?export=view&id=1h0J3MwZqbJ8GOkkpsdAAcbOKoGShenhI","destillery":"","alcohol":39,"stock":true,"price":5785.5},{"id":"#004","isCombo":false,"category":"Fernet","type":"Fernet","name":"Fernet buhero 700","description":"De aroma intenso, especiado y herbáceo. Su sabor balsámico contiene notas de clavo de olor, canela y regaliz.","imageID":"1rVFT4MStIRVCmaVJ4qRpevqPNw_cTmSn","imageURL":"https://drive.google.com/uc?export=view&id=1rVFT4MStIRVCmaVJ4qRpevqPNw_cTmSn","destillery":"","alcohol":39,"stock":false,"price":7221.9}]',
  },
  {
    category: 'Vodka',
    'firestoreName-ID': 'lvEguBoqScd2dCzisjdh',
    firestoreName: 'projects/stock-backend-392114/databases/(default)/documents/categories-test/lvEguBoqScd2dCzisjdh',
    data: '[{"id":"#005","isCombo":false,"category":"Vodka","type":"Vodka","name":"Absolut clasico 750","description":"Caracter distintivo del grano de trigo, seguido de un toque a frutas secas.","imageID":"14ypaQ6jreXoNVlL3ElLaULQ5oZe8mf93","imageURL":"https://drive.google.com/uc?export=view&id=14ypaQ6jreXoNVlL3ElLaULQ5oZe8mf93","destillery":"","alcohol":40,"stock":true,"price":17680},{"id":"#006","isCombo":false,"category":"Vodka","type":"Vodka","name":"Absolut raspberry 750","description":"Notas intensamente aromáticas de frambuesas dulces","imageID":"1xTxdMgpbZUdq8VUFdWTPDVw79FyA5Gah","imageURL":"https://drive.google.com/uc?export=view&id=1xTxdMgpbZUdq8VUFdWTPDVw79FyA5Gah","destillery":"","alcohol":38,"stock":true,"price":19578},{"id":"#007","isCombo":false,"category":"Vodka","type":"Vodka","name":"Absolut mango 750","description":"Notas de mango maduros junto con un sabor a piña y maracuyá","imageID":"1FYuyLCcIwBe6mra6rG-Ual5VZ_59yYx9","imageURL":"https://drive.google.com/uc?export=view&id=1FYuyLCcIwBe6mra6rG-Ual5VZ_59yYx9","destillery":"","alcohol":40,"stock":true,"price":19578},{"id":"#008","isCombo":false,"category":"Vodka","type":"Vodka","name":"Absolut mandarina 750","description":"Sabor a mandarina mezclados con un toque de la cáscara de naranja.","imageID":"1xuCe_se5t6WLgCqpaFDdKvd6vxxCefpg","imageURL":"https://drive.google.com/uc?export=view&id=1xuCe_se5t6WLgCqpaFDdKvd6vxxCefpg","destillery":"","alcohol":40,"stock":true,"price":19578},{"id":"#009","isCombo":false,"category":"Vodka","type":"Vodka","name":"Absolut Lime 750","description":"Notas citricas de limon y lima.","imageID":"1OeQUqUg0Avj-WAkANc9jgMgA7266YB1x","imageURL":"https://drive.google.com/uc?export=view&id=1OeQUqUg0Avj-WAkANc9jgMgA7266YB1x","destillery":"","alcohol":40,"stock":true,"price":19578},{"id":"#010","isCombo":false,"category":"Vodka","type":"Vodka","name":"Absolut vainilla 750","description":"Combina el carácter de la vainilla, el tofe y sabores de caramelo","imageID":"1r7-Hsbi1G6vcdP53v3SGeBxnKHMIXXsJ","imageURL":"https://drive.google.com/uc?export=view&id=1r7-Hsbi1G6vcdP53v3SGeBxnKHMIXXsJ","destillery":"","alcohol":40,"stock":false,"price":0},{"id":"#011","isCombo":false,"category":"Vodka","type":"Vodka","name":"Absolut extrakt 750","description":"Sabor cálido y especiado del cardamomo verde","imageID":"1JPjp6ZTXO1tbbbr2KN5L8L3pa_Yls4qI","imageURL":"https://drive.google.com/uc?export=view&id=1JPjp6ZTXO1tbbbr2KN5L8L3pa_Yls4qI","destillery":"","alcohol":35,"stock":false,"price":0},{"id":"#012","isCombo":false,"category":"Vodka","type":"Vodka","name":"Smirnoff clasico 700","description":"Obtenido por triple destilación del alcohol de grano, y filtrado por carbón.","imageID":"14SasdXqyA8xc9lSrZ5XqRnegvJkjPTLF","imageURL":"https://drive.google.com/uc?export=view&id=14SasdXqyA8xc9lSrZ5XqRnegvJkjPTLF","destillery":"","alcohol":40,"stock":true,"price":4708.2},{"id":"#013","isCombo":false,"category":"Vodka","type":"Vodka","name":"Smirnoff citric 700","description":"Fusiona pomelo rosado y lima en un mix perfecto de sabores","imageID":"1KX6HVkUf4oNmG5-W4-XckwCCFbHGHmNT","imageURL":"https://drive.google.com/uc?export=view&id=1KX6HVkUf4oNmG5-W4-XckwCCFbHGHmNT","destillery":"","alcohol":29,"stock":true,"price":5240.2},{"id":"#014","isCombo":false,"category":"Vodka","type":"Vodka","name":"Smirnoff apple 700","description":"Sabor agridulce de las manzanas verdes","imageID":"1Brg61ukl_8Fd_1g1FhXfxj8_Yu4DpMBh","imageURL":"https://drive.google.com/uc?export=view&id=1Brg61ukl_8Fd_1g1FhXfxj8_Yu4DpMBh","destillery":"","alcohol":29,"stock":true,"price":5240.2},{"id":"#015","isCombo":false,"category":"Vodka","type":"Vodka","name":"Smirnoff watermelon 700","description":"Sabor a sandía rosa para un sabor dulce y refrescante","imageID":"10c2bv6jMdqS8xESm2VM6H3bOPfEe62um","imageURL":"https://drive.google.com/uc?export=view&id=10c2bv6jMdqS8xESm2VM6H3bOPfEe62um","destillery":"","alcohol":29,"stock":true,"price":5240.2},{"id":"#016","isCombo":false,"category":"Vodka","type":"Vodka","name":"Smirnoff raspberry 700","description":"Vodka aromático, puro y fresco, sabor frambuesa.","imageID":"1uJ-Zx2n65_FqsYXVyJXR4nFFDW50CWrK","imageURL":"https://drive.google.com/uc?export=view&id=1uJ-Zx2n65_FqsYXVyJXR4nFFDW50CWrK","destillery":"","alcohol":29,"stock":true,"price":5240.2},{"id":"#017","isCombo":false,"category":"Vodka","type":"Vodka","name":"Smirnoff Tropical 700","description":"Saborizantes de mango, guayaba, maracuyá","imageID":"199a5B9X7BCsvwe-uiBncDav_1M5oja53","imageURL":"https://drive.google.com/uc?export=view&id=199a5B9X7BCsvwe-uiBncDav_1M5oja53","destillery":"","alcohol":29,"stock":true,"price":5240.2},{"id":"#018","isCombo":false,"category":"Vodka","type":"Vodka","name":"Smirnoff citrus 700","description":"Sabores de azucarado cáscara de cítricos y un toque de calor.","imageID":"1KX6HVkUf4oNmG5-W4-XckwCCFbHGHmNT","imageURL":"https://drive.google.com/uc?export=view&id=1KX6HVkUf4oNmG5-W4-XckwCCFbHGHmNT","destillery":"","alcohol":29,"stock":false,"price":0},{"id":"#019","isCombo":false,"category":"Vodka","type":"Vodka","name":"Sky clasico 700","description":"Levemente astringente, cálido, de textura suave, con leve amargor.","imageID":"1hHNSQ3OY9LsznAukV1rU6zLFhFznwdd6","imageURL":"https://drive.google.com/uc?export=view&id=1hHNSQ3OY9LsznAukV1rU6zLFhFznwdd6","destillery":"","alcohol":40,"stock":true,"price":4814.6},{"id":"#020","isCombo":false,"category":"Vodka","type":"Vodka","name":"Sky frambuesa 700","description":"Notas florales frescas con un final que es el verdadero sabor a puré de frambuesas","imageID":"1AAhfbwrBlH9NN1ueAY_VBzH6EmxEgR1L","imageURL":"https://drive.google.com/uc?export=view&id=1AAhfbwrBlH9NN1ueAY_VBzH6EmxEgR1L","destillery":"","alcohol":29,"stock":true,"price":5453},{"id":"#021","isCombo":false,"category":"Vodka","type":"Vodka","name":"Sky anana 700","description":"Sabor a piña y ligeras notas a vainilla","imageID":"10-dqNlAkmF9-5q_QwX3twykGovpxBgDR","imageURL":"https://drive.google.com/uc?export=view&id=10-dqNlAkmF9-5q_QwX3twykGovpxBgDR","destillery":"","alcohol":29,"stock":true,"price":5453}]',
  },
];
