export const buildedStockData = [
  {
    id: '#001',
    category: 'Fernet',
    type: 'Fernet',
    name: 'Fernet branca 1L',
    description: 'Elaborada a base de hierbas (mirra, ruibarbo, manzanilla, cardamomo y azafrán, entre otras)',
    imageID: '1ToG5gKlwY8nKk8uXgHGqNFk_qDIYMpQM',
    imageURL: 'https://drive.google.com/uc?export=view&id=1ToG5gKlwY8nKk8uXgHGqNFk_qDIYMpQM',
    destillery: '',
    alcohol: 39,
    stock: true,
    price: 11704,
    isCombo: false,
  },
  {
    id: '#002',
    category: 'Fernet',
    type: 'Fernet',
    name: 'Fernet branca 750',
    description: 'Elaborada a base de hierbas (mirra, ruibarbo, manzanilla, cardamomo y azafrán, entre otras)',
    imageID: 'testing-no-image-url',
    imageURL: 'testing-no-image-url',
    destillery: '',
    alcohol: 39,
    stock: true,
    price: 8911,
    isCombo: false,
  },
  {
    id: '#007',
    category: 'Vodka',
    type: 'Vodka',
    name: 'Absolut mango 750',
    description: 'Notas de mango maduros junto con un sabor a piña y maracuyá',
    imageID: '1FYuyLCcIwBe6mra6rG-Ual5VZ_59yYx9',
    imageURL: 'https://drive.google.com/uc?export=view&id=1FYuyLCcIwBe6mra6rG-Ual5VZ_59yYx9',
    destillery: '',
    alcohol: 40,
    stock: true,
    price: 19578,
    isCombo: false,
  },
  {
    id: '#008',
    category: 'Vodka',
    type: 'Vodka',
    name: 'Absolut mandarina 750',
    description: 'Sabor a mandarina mezclados con un toque de la cáscara de naranja.',
    imageID: '1xuCe_se5t6WLgCqpaFDdKvd6vxxCefpg',
    imageURL: 'https://drive.google.com/uc?export=view&id=1xuCe_se5t6WLgCqpaFDdKvd6vxxCefpg',
    destillery: '',
    alcohol: 40,
    stock: true,
    price: 19578,
    isCombo: false,
  },
  {
    id: '#009',
    category: 'Vodka',
    type: 'Vodka',
    name: 'Absolut Lime 750',
    description: 'Notas citricas de limon y lima.',
    imageID: '1OeQUqUg0Avj-WAkANc9jgMgA7266YB1x',
    imageURL: 'https://drive.google.com/uc?export=view&id=1OeQUqUg0Avj-WAkANc9jgMgA7266YB1x',
    destillery: '',
    alcohol: 40,
    stock: true,
    price: 19578,
    isCombo: false,
  },
  {
    id: '#010',
    category: 'Vodka',
    type: 'Vodka',
    name: 'Absolut vainilla 750',
    description: 'Combina el carácter de la vainilla, el tofe y sabores de caramelo',
    imageID: '1r7-Hsbi1G6vcdP53v3SGeBxnKHMIXXsJ',
    imageURL: 'https://drive.google.com/uc?export=view&id=1r7-Hsbi1G6vcdP53v3SGeBxnKHMIXXsJ',
    destillery: '',
    alcohol: 40,
    stock: false,
    price: 0,
    isCombo: false,
  },
];

export const testStockCache = [
  {
    category: 'Fernet',
    'firestoreName-ID': 'ZTKZiMQzMZudQdxT1djz',
    firestoreName: 'projects/stock-backend-392114/databases/(default)/documents/categories-test/ZTKZiMQzMZudQdxT1djz',
    data: '[{"id":"#001","category":"Fernet","type":"Fernet","name":"Fernet branca 1L","description":"Elaborada a base de hierbas (mirra, ruibarbo, manzanilla, cardamomo y azafrán, entre otras)","imageID":"1ToG5gKlwY8nKk8uXgHGqNFk_qDIYMpQM","imageURL":"https://drive.google.com/uc?export=view&id=1ToG5gKlwY8nKk8uXgHGqNFk_qDIYMpQM","destillery":"","alcohol":39,"stock":true,"price":11704,"isCombo":false},{"id":"#002","category":"Fernet","type":"Fernet","name":"Fernet branca 750","description":"Elaborada a base de hierbas (mirra, ruibarbo, manzanilla, cardamomo y azafrán, entre otras)","imageID":"testing-no-image-url","imageURL":"testing-no-image-url","destillery":"","alcohol":39,"stock":true,"price":8911,"isCombo":false}]',
  },
  {
    category: 'Vodka',
    'firestoreName-ID': 'lvEguBoqScd2dCzisjdh',
    firestoreName: 'projects/stock-backend-392114/databases/(default)/documents/categories-test/lvEguBoqScd2dCzisjdh',
    data: '[{"id":"#007","category":"Vodka","type":"Vodka","name":"Absolut mango 750","description":"Notas de mango maduros junto con un sabor a piña y maracuyá","imageID":"1FYuyLCcIwBe6mra6rG-Ual5VZ_59yYx9","imageURL":"https://drive.google.com/uc?export=view&id=1FYuyLCcIwBe6mra6rG-Ual5VZ_59yYx9","destillery":"","alcohol":40,"stock":true,"price":19578,"isCombo":false},{"id":"#008","category":"Vodka","type":"Vodka","name":"Absolut mandarina 750","description":"Sabor a mandarina mezclados con un toque de la cáscara de naranja.","imageID":"1xuCe_se5t6WLgCqpaFDdKvd6vxxCefpg","imageURL":"https://drive.google.com/uc?export=view&id=1xuCe_se5t6WLgCqpaFDdKvd6vxxCefpg","destillery":"","alcohol":40,"stock":true,"price":19578,"isCombo":false},{"id":"#009","category":"Vodka","type":"Vodka","name":"Absolut Lime 750","description":"Notas citricas de limon y lima.","imageID":"1OeQUqUg0Avj-WAkANc9jgMgA7266YB1x","imageURL":"https://drive.google.com/uc?export=view&id=1OeQUqUg0Avj-WAkANc9jgMgA7266YB1x","destillery":"","alcohol":40,"stock":true,"price":19578,"isCombo":false},{"id":"#010","category":"Vodka","type":"Vodka","name":"Absolut vainilla 750","description":"Combina el carácter de la vainilla, el tofe y sabores de caramelo","imageID":"1r7-Hsbi1G6vcdP53v3SGeBxnKHMIXXsJ","imageURL":"https://drive.google.com/uc?export=view&id=1r7-Hsbi1G6vcdP53v3SGeBxnKHMIXXsJ","destillery":"","alcohol":40,"stock":false,"price":0,"isCombo":false}]',
  },
];
